// <auto-generated />
using System;
using BigDataTechnology.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BigDataTechnology.DATA.Migrations
{
    [DbContext(typeof(BigDataTechnologyDbContext))]
    [Migration("20210212071819_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BigDataTechnology.Entities.Models.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CurrentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentTemprature")
                        .HasColumnType("float");

                    b.Property<DateTime>("HighestDateTimeInThisWeek")
                        .HasColumnType("datetime2");

                    b.Property<double>("HighestTempratureInThisWeek")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LowestDateTimeInThisWeek")
                        .HasColumnType("datetime2");

                    b.Property<double>("LowestTempratureInThisWeek")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.ToTable("WeatherForecast");
                });
#pragma warning restore 612, 618
        }
    }
}
